<?php
/**
 * Ticketmatic theater widget integration.
 */
namespace Jeero\Theaters;

use Jeero\Subscriptions\Subscription;

/**
 * Ticketmatic theater adapter.
 *
 * Signed widget URLs are generated by the Jeero service and imported as
 * canonical event data. The WordPress plugin never handles widget secrets.
 *
 * @since 1.35
 */
class Ticketmatic extends Theater {

	public $display_name = 'Ticketmatic';

	/**
	 * Get the widgets supported by Ticketmatic v1.
	 *
	 * @return string[]
	 */
	public function get_supported_widgets(): ?array {

		return array( 'tickets_button', 'tickets_inline' );

	}

	/**
	 * Render the server-signed addtickets widget for the current event.
	 *
	 * Only presentation arguments are honored. In particular, a URL supplied
	 * through shortcode attributes can never replace the imported signed URL.
	 *
	 * @param Subscription $subscription Jeero subscription.
	 * @param array        $args         Render arguments.
	 * @return string
	 */
	public function get_tickets_inline_widget_html( Subscription $subscription, array $args = array() ): string {

		if ( ! $this->is_active_subscription( $subscription ) ) {
			return '';
		}

		$context = Widgets\get_ticket_context( $args, $subscription->ID );
		$url     = $context['tickets_inline_url'];

		if ( '' === $url || ! $this->is_embeddable_widget_url( $url ) ) {
			return '';
		}

		$title  = ! empty( $args['title'] ) && is_scalar( $args['title'] ) ? (string) $args['title'] : __( 'Tickets', 'jeero' );
		$width  = ! empty( $args['width'] ) && is_scalar( $args['width'] ) ? (string) $args['width'] : '100%';
		$height = ! empty( $args['height'] ) ? absint( $args['height'] ) : 800;

		return sprintf(
			'<iframe src="%s" class="jeero-tickets-inline jeero-ticketmatic-addtickets" title="%s" loading="lazy" width="%s" height="%d"></iframe>',
			esc_url( $url ),
			esc_attr( $title ),
			esc_attr( $width ),
			$height
		);

	}

	/**
	 * Check whether a widget URL uses a sibling custom domain of this site.
	 *
	 * @param string $url Signed Ticketmatic widget URL.
	 * @return bool
	 */
	protected function is_embeddable_widget_url( string $url ): bool {

		$widget_host = strtolower( (string) wp_parse_url( $url, PHP_URL_HOST ) );
		$site_host   = strtolower( (string) wp_parse_url( home_url( '/' ), PHP_URL_HOST ) );
		$allowed     = is_ssl() ? 'https' === wp_parse_url( $url, PHP_URL_SCHEME ) : in_array( wp_parse_url( $url, PHP_URL_SCHEME ), array( 'http', 'https' ), true );

		if ( $allowed && '' !== $widget_host && '' !== $site_host ) {
			$site_domain = 0 === strpos( $site_host, 'www.' ) ? substr( $site_host, 4 ) : $site_host;
			$allowed     = $widget_host === $site_domain || $this->host_ends_with( $widget_host, '.' . $site_domain );
		} else {
			$allowed = false;
		}

		/**
		 * Filters whether a signed Ticketmatic widget URL may be embedded.
		 *
		 * @param bool   $allowed Whether the URL may be embedded.
		 * @param string $url     Signed Ticketmatic widget URL.
		 */
		return (bool) apply_filters( 'jeero/ticketmatic/widget_url_is_embeddable', $allowed, $url );

	}

	/**
	 * Check a host suffix without requiring PHP 8 string helpers.
	 *
	 * @param string $host   Hostname.
	 * @param string $suffix Expected suffix.
	 * @return bool
	 */
	protected function host_ends_with( string $host, string $suffix ): bool {

		return strlen( $host ) >= strlen( $suffix ) && substr( $host, -strlen( $suffix ) ) === $suffix;

	}
}
